# Generated by Django 6.0.4 on 2026-05-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0002_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='University_id',
            field=models.CharField(max_length=10),
        ),
    ]
